[package]
name = "netrat"
version = "0.1.0"
edition = "2021"
default-run = "netrat"

[[bin]]
name = "netrat"
path = "src/main.rs"

[[bin]]
name = "echo-server"
path = "src/bin/echo_server.rs"

[dependencies]
